- name: get facts playbook
  hosts: localhost
  connection: local
  tasks:
  - name: error handling block
    block:
      - name: debug
        debug:
          msg: "You will see failed tasks after this"

      - name: failed task in block
        command: /bin/false

      - name: unreachable block debug
        debug:
          msg: "You won't see this message"
    rescue:
      - name: emergency debug
        debug:
          msg: "This task will be executed in case of block tasks failure"

      - name: failed task in rescue
        command: /bin/false
      
      - name: unreachable rescue debug
        debug:
          msg: "You won't see this message"
    always:
      - name: final debug
        debug:
          msg: "This task will always be executed"
