---
- name: install MariaDB
  block:
    - name: Install 'mariadb-server' and 'MySQL-python' packages
      package:
        name:
          - mariadb-server
          - MySQL-python
        state: latest

    - name: Ensure 'mariadb' service is started and enabled
      systemd:
        name: mariadb
        state: started
        enabled: yes

    - name: Create "{{ db_name }}" database
      mysql_db:
        name: "{{ db_name }}"
        encoding: utf8
        state: present

    - name: >
        Create database user "{{ db_user }}" with "{{ db_password }}"
        and "{{ db_name }}".*:ALL privelege
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: "{{ db_name }}.*:ALL"
        state: present
      no_log: true
