---
- name: include_role tasks
  hosts: localhost
  connection: local
  vars: 
    test_part: test
  # pre_tasks:
  #   - name: set fact
  #     set_fact:
  #       test_part: test
  tasks:
    - name: task before role
      debug:
        msg: "This task executes before roles' tasks"

    - name: static role import_role
      import_role:
        name: "{{ test_part }}role"
      vars: 
        custom_var: 42
      tags: tagA
      when: test_part == "test"

    - name: task after role
      debug:
        msg: "This task executes after roles' tasks" 
