---
- name: execute tasks depending on OS version
  gather_facts: true
  hosts: nodes
  tasks:
    - name: set os_distrib_version fact
      set_fact: 
        os_distrib: "{{ ansible_facts.distribution }}"    
    - name:
      debug: 
        var: os_distrib
    - name: set os_distrib_version fact
      set_fact: 
        os_distrib_version: "{{ ansible_facts.distribution_version }}"    
    - name:
      debug: 
        var: os_distrib_version
    - name: execute tasks file dynamically
      import_tasks: centos7.7.yaml
      when:
        - os_distrib | lower == "centos"
        - os_distrib_version | string == "7.7"
